package com.dsharnessmobile.shell

import android.content.Context
import android.media.MediaScannerConnection
import android.os.Environment
import android.util.Log
import java.io.File
import java.io.ByteArrayInputStream
import java.io.FileOutputStream
import java.nio.file.Files
import java.security.MessageDigest
import java.util.UUID
import java.util.zip.ZipInputStream
import org.apache.commons.compress.archivers.tar.TarArchiveEntry
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream
import org.apache.commons.compress.compressors.xz.XZCompressorInputStream

/**
 * Owns the embedded Termux environment snapshot: first-launch extraction into
 * filesDir/usr and the dsh engine process lifecycle (PATH/LD_LIBRARY_PATH/HOME
 * injected explicitly — the snapshot is self-sufficient, no Termux app needed).
 */
class EngineManager(private val context: Context, private val pickToken: String? = null) {

  val usrDir = File(context.filesDir, "usr")
  val homeDir = File(context.filesDir, "home")

  /**
   * Public export repo: /storage/emulated/0/Documents/dshdata.
   * Holds only user-initiated session zip exports (exports/) plus a .nomedia anti-scan marker;
   * all runtime user data lives back in private app data (files/home/.dsh).
   */
  val dshDataDir: File
    get() {
      val publicDocs = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS)
        ?: File(context.filesDir, "dshdata-fallback")
      return File(publicDocs, "dshdata")
    }
  private val nodeBin = File(usrDir, "bin/node")
  private val dshBin = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/lib/bin.js")
  private val pkgClientAsset = "pkg-android.js"
  private val pkgClientFile = File(context.filesDir, pkgClientAsset)
  private val pptSetupAsset = "setup_ppt_env.sh"
  private val pptSetupFile = File(homeDir, ".dsh/tools/$pptSetupAsset")
  private val pptSkillSetupFile = File(homeDir, ".dsh/skills/ppt-master/scripts/$pptSetupAsset")
  private val pptSkillDir = File(homeDir, ".dsh/skills/ppt-master")
  private val pptSkillMarker = File(pptSkillDir, ".dsh-bundled-sha256")
  private var engineProcess: Process? = null

  /** Consecutive healthy probe ticks since the last update swap (update-v2 confirmation state). */
  private var updateHealthTicks = 0

  val engineReady: Boolean get() = nodeBin.exists()

  /**
   * Deploy the undo emergency CLI (assets/undo-emergency.mjs → filesDir).
   * Idempotent: content equals the asset → skip. Missing node still succeeds
   * (the file itself is versioned with the app); UndoGate checks child exit code.
   */
  fun deployUndoCli() {
    try {
      val asset = "undo-emergency.mjs"
      if (context.assets.open(asset).use { it.readBytes() }.let { b ->
          File(context.filesDir, asset).takeIf { it.exists() }?.readBytes()?.contentEquals(b) != true
        }) {
        context.assets.open(asset).use { input ->
          File(context.filesDir, asset).outputStream().use { input.copyTo(it) }
        }
        Log.i(TAG, "undo emergency CLI deployed")
      }
    } catch (t: Throwable) {
      Log.e(TAG, "undo CLI deploy failed (non-fatal): " + t.message)
    }
  }

  /** Embedded snapshot fingerprint (assets/snapshot.sha256, generated by build-release.ps1). */
  private fun bundledFingerprint(): String = try {
    context.assets.open("snapshot.sha256").bufferedReader().use { it.readText().trim() }
  } catch (_: Exception) {
    ""
  }

  private fun fingerprintFile(): File = File(context.filesDir, ".snapshot-fingerprint")

  /**
   * Whether the snapshot is extracted and matches the embedded version: node exists + fingerprint match.
   * Upgrade lesson (v0.10.5→v0.10.6): engineReady only checked node existence, so an upgrade never
   * re-extracted → old plugins kept running (injection-guard fixes etc. never took effect).
   */
  fun snapshotFresh(): Boolean {
    if (!nodeBin.exists()) return false
    val fp = bundledFingerprint()
    if (fp.isEmpty()) return true // no fingerprint file (legacy build): don't force a re-extract
    return fingerprintFile().exists() && fingerprintFile().readText().trim() == fp
  }

  /**
   * Upgrade/snapshot change: back up user data → fully re-extract the embedded snapshot → restore user
   * data → write the fingerprint. The snapshot strips sessions/storages/attachments/credentials/settings
   * (see make-snapshot.sh), so a plain re-extract would "lose" that private data — backup first, restore
   * after; factory profiles (cordis*.yml/node_modules) follow the snapshot (manual patches must be
   * re-applied on top of the new baseline). On any failure: restore the backup and keep the old runtime
   * (retried on next start).
   */
  fun refreshSnapshot(onProgress: (Long, Long) -> Unit): Boolean {
    val backup = File(context.filesDir, ".dsh-backup")
    val dsh = File(homeDir, ".dsh")
    try {
      if (dsh.exists()) {
        backup.deleteRecursively()
        // Upgrade-residue tolerance (v0.12.4): profile node_modules may carry dangling symlinks
        // pointing at packages that no longer exist (npm layout changes) — copyRecursively's
        // exists() check on a dangling link throws NoSuchFileException and fails the whole refresh.
        // Drop broken links before backing up (profiles follow the snapshot; the backup omits them).
        dsh.walkTopDown().forEach { if (java.nio.file.Files.isSymbolicLink(it.toPath()) && !it.exists()) it.delete() }
        dsh.copyRecursively(backup)
      }
      val ok = extractSnapshot(onProgress)
      if (!ok) {
        restoreUserData(backup, dsh)
        Log.e(TAG, "snapshot refresh: extract failed, kept old runtime")
        return false
      }
      restoreUserData(backup, dsh)
      backup.deleteRecursively()
      fingerprintFile().writeText(bundledFingerprint())
      Log.i(TAG, "snapshot refreshed (fingerprint " + bundledFingerprint().take(12) + ")")
      return true
    } catch (t: Throwable) {
      restoreUserData(backup, dsh)
      Log.e(TAG, "snapshot refresh failed; kept old runtime", t)
      return false
    }
  }

  /** Restore the snapshot-stripped user data dirs/files (copied back from the backup into private .dsh).
   *  Never throws (Review 2026-08-18 R2): refreshSnapshot's failure branch calls this on a background
   *  thread, so a restore failure must not escape — otherwise the exception kills the thread and the UI
   *  hangs on "Updating runtime…" with no message. Failures only log; the backup is kept for a retry. */
  private fun restoreUserData(backup: File, dsh: File) {
    if (!backup.exists()) return
    for (name in listOf(
      "sessions", "storages", "attachments",
      ".credentials.yaml", "settings.yaml", ".anonymous-user-id", ".private-layout",
    )) {
      try {
        val src = File(backup, name)
        if (!src.exists()) continue
        val dst = File(dsh, name)
        if (dst.exists()) dst.deleteRecursively()
        src.copyRecursively(dst)
      } catch (t: Throwable) {
        Log.e(TAG, "restore user data failed for $name; backup kept at " + backup.absolutePath, t)
      }
    }
  }

  /** Process-level start guard (MainActivity and EngineService each construct their own EngineManager;
   *  instance fields are invisible across them — the double-start race needs companion-level CAS). */
  private val starting: Boolean
    get() = STARTING.get()

  /**
   * Extract the bundled snapshot archive into filesDir. Runs on any thread;
   * callers own the progress UI.
   * @param onProgress bytesDone, bytesTotal.
   * @returns true on success.
   */
  fun extractSnapshot(onProgress: (Long, Long) -> Unit): Boolean {
    return try {
      val fd = context.assets.openFd("snapshot.tar.xz")
      SnapshotExtractor.extract(context.assets.open("snapshot.tar.xz"), fd.length, usrDir.parentFile, onProgress)
      homeDir.mkdirs()
      true
    } catch (t: Throwable) {
      Log.e(TAG, "snapshot extract failed", t)
      false
    }
  }

  /**
   * Ensure the private DSH_HOME data layout is ready (idempotent, called from a background thread).
   *
   * Since v0.10.5 all runtime data lives in private app data; Documents/dshdata stays only as the
   * user-initiated export repo (exports/ + .nomedia). This method:
   *  - on a first/clean install: sets up the private .dsh layout and the public export repo;
   *  - when it detects a pre-v0.10.4 public migration layout (.migrated-from or private symlinks):
   *    performs a reverse migration, copying sessions/storages/attachments/profiles/settings.yaml
   *    back into private storage and cleaning up the public leftovers;
   *  - on any failure keeps the public data; the engine still starts with a private DSH_HOME and
   *    retries next time.
   *
   * DSH_HOME always stays in the private domain: the profiles/node_modules flat-fallback symlink
   * mechanism depends on the app-private domain (public FUSE forbids symlinks), so DSH_HOME must
   * never be migrated wholesale.
   */
  fun ensurePrivateDshData(): File {
    val dshData = dshDataDir
    val privateDsh = File(homeDir, ".dsh")
    privateDsh.mkdirs()
    val privateMarker = File(privateDsh, ".private-layout")
    if (privateMarker.exists()) {
      ensurePublicExportRepo(dshData)
      return privateDsh
    }
    if (isLegacyPublicLayout(dshData, privateDsh)) {
      try {
        reverseMigrate(dshData, privateDsh)
        privateMarker.writeText("private")
        ensurePublicExportRepo(dshData)
        Log.i(TAG, "dshdata reverse migration done -> " + privateDsh.absolutePath)
      } catch (t: Throwable) {
        // A migration failure must not block startup: DSH_HOME stays private, the engine works, retry later.
        Log.e(TAG, "dshdata reverse migration failed; keeping public data", t)
      }
    } else {
      // Clean install or already-private layout: just mark it, no migration needed.
      try {
        privateMarker.writeText("private")
      } catch (t: Throwable) {
        Log.w(TAG, "private layout marker write failed", t)
      }
      ensurePublicExportRepo(dshData)
    }
    return privateDsh
  }

  /** Detect the pre-v0.10.4 public migration layout. */
  private fun isLegacyPublicLayout(dshData: File, privateDsh: File): Boolean {
    if (File(dshData, ".migrated-from").exists()) return true
    for (name in listOf("sessions", "storages", "attachments")) {
      if (isSymlink(File(privateDsh, name))) return true
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        if (isSymlink(File(privateDsh, "profiles/$profile/$name"))) return true
      }
    }
    return false
  }

  /** Reverse migration: copy public data back into private storage, clean up the public leftovers. */
  private fun reverseMigrate(dshData: File, privateDsh: File) {
    for (name in listOf("sessions", "storages", "attachments")) {
      reverseMigrateDir(File(privateDsh, name), File(dshData, name))
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        reverseMigrateFile(
          File(privateDsh, "profiles/$profile/$name"),
          File(dshData, "profiles/$profile/$name"),
        )
      }
    }
    reverseMigrateFile(File(privateDsh, "settings.yaml"), File(dshData, "settings.yaml"))

    // Clean up stale public data (conflicts were renamed *.public-backup, so they're untouched).
    val removedPaths = mutableListOf<String>()
    for (name in listOf("sessions", "storages", "attachments", "profiles", "settings.yaml", ".migrated-from")) {
      val f = File(dshData, name)
      if (f.exists()) {
        removedPaths += f.absolutePath
        if (!f.deleteRecursively()) {
          throw java.io.IOException("failed to delete public path " + f.absolutePath)
        }
      }
    }
    // Tell MediaScanner the old public subdirs are gone, clearing the fake video entries it indexed.
    if (removedPaths.isNotEmpty()) {
      try {
        MediaScannerConnection.scanFile(context, removedPaths.toTypedArray(), null, null)
      } catch (t: Throwable) {
        Log.w(TAG, "media scan cleanup failed", t)
      }
    }
  }

  /** Dir-level reverse migration: drop the private symlink, copy the public entity back with a verified copy, then delete the public source. */
  private fun reverseMigrateDir(privateDir: File, publicDir: File) {
    if (isSymlink(privateDir)) {
      Files.delete(privateDir.toPath())
    }
    if (!publicDir.isDirectory) return
    if (privateDir.isDirectory) {
      if (privateDir.listFiles()?.isNotEmpty() == true) {
        // Conflict: the private entity wins; the public copy is kept aside for review.
        val backup = uniqueBackup(publicDir)
        if (!publicDir.renameTo(backup)) {
          throw java.io.IOException("failed to backup public dir " + publicDir.absolutePath)
        }
        Log.w(TAG, "private " + privateDir.absolutePath + " exists; public kept as " + backup.absolutePath)
        return
      }
      privateDir.deleteRecursively()
    }
    privateDir.parentFile?.mkdirs()
    copyTreeVerified(publicDir, privateDir)
    if (!publicDir.deleteRecursively()) {
      throw java.io.IOException("failed to delete public source " + publicDir.absolutePath)
    }
  }

  /** File-level reverse migration: drop the private symlink, copy the public file back, then delete the public source. */
  private fun reverseMigrateFile(privateFile: File, publicFile: File) {
    if (isSymlink(privateFile)) {
      Files.delete(privateFile.toPath())
    }
    if (!publicFile.isFile) return
    if (privateFile.exists()) {
      if (privateFile.length() > 0) {
        // The public file is the post-migration active copy (settings/profiles); the public one wins,
        // and the stale private entity is kept as a backup rather than silently deleted.
        val backup = uniquePrivateBackup(privateFile)
        if (!privateFile.renameTo(backup)) {
          throw java.io.IOException("failed to backup private file " + privateFile.absolutePath)
        }
        Log.w(TAG, "private file backed up as " + backup.absolutePath)
      } else {
        privateFile.delete()
      }
    }
    privateFile.parentFile?.mkdirs()
    publicFile.copyTo(privateFile, overwrite = true)
    if (privateFile.length() != publicFile.length()) {
      throw java.io.IOException("copy verification failed for " + publicFile.absolutePath)
    }
    if (!publicFile.delete()) {
      throw java.io.IOException("failed to delete public source " + publicFile.absolutePath)
    }
  }

  /** Ensure the public export repo exists: root dir + .nomedia + exports/. */
  private fun ensurePublicExportRepo(dshData: File) {
    try {
      dshData.mkdirs()
      File(dshData, ".nomedia").writeText("")
      File(dshData, "exports").mkdirs()
    } catch (t: Throwable) {
      Log.w(TAG, "public export repo setup failed", t)
    }
  }

  private fun isSymlink(file: File): Boolean = Files.isSymbolicLink(file.toPath())

  private fun uniqueBackup(publicFile: File): File {
    var candidate = File(publicFile.parentFile, publicFile.name + ".public-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(publicFile.parentFile, publicFile.name + ".public-backup-" + i)
      i++
    }
    return candidate
  }

  private fun uniquePrivateBackup(privateFile: File): File {
    var candidate = File(privateFile.parentFile, privateFile.name + ".private-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(privateFile.parentFile, privateFile.name + ".private-backup-" + i)
      i++
    }
    return candidate
  }

  /** Recursively copy a directory tree, verifying the file count and total size. */
  private fun copyTreeVerified(src: File, dst: File) {
    dst.mkdirs()
    src.listFiles()?.forEach { f ->
      val target = File(dst, f.name)
      if (f.isDirectory) {
        copyTreeVerified(f, target)
      } else {
        f.copyTo(target, overwrite = true)
      }
    }
    val srcFiles = src.walkBottomUp().filter { it.isFile }.toList()
    val dstFiles = dst.walkBottomUp().filter { it.isFile }.toList()
    val srcSize = srcFiles.sumOf { it.length() }
    val dstSize = dstFiles.sumOf { it.length() }
    if (srcFiles.size != dstFiles.size || srcSize != dstSize) {
      throw java.io.IOException("copy verification failed for " + src.absolutePath)
    }
  }

  /**
   * Runtime patches: overlay fix files from assets/patched onto the corresponding snapshot
   * locations (idempotent). Overlayed fixes (all marked by a sentinel string in the target file,
   * so they are re-applied automatically after a snapshot refresh/re-extract):
   *  - primitives-index.js: clipboard fallback for WebViews where navigator.clipboard is denied
   *  - attachment-local-index.js: Android link(2) blocked by sepolicy → copyFile fallback + EACCES tolerance
   *  - web-frontend-index.html: immersive viewport-fit=cover patch
   *  - llm-deepseek: NOT patched — dsh 0.1.1-rc.2 bundles deepseek-v4-flash-vision-exp natively
   *    with the corrected image-request serialization (see applyRuntimePatches).
   *  - session-persistence-jsonl-index.js / fs-local-index.js: Android link(2) fallback — dsh
   *    0.1.1-rc.1 dropped the EACCES/EPERM/ENOTSUP → rename fallback that rc.8 shipped; Android
   *    app domains forbid link(2) (sepolicy), re-add it as a full-file overlay (as in rc.8).
   *  Patches use a content fingerprint (no fixed marker), so an updated asset re-applies on
   *  upgrade instead of being skipped by a stale marker string (the v1→v2 update bug).
   * (v0.12.4 rc8 removed the onImagePicked/llm-deepseek/textzoom patches — rc8's native image
   * request support and no-cache hardening supersede them.)
   */
  private fun applyRuntimePatches() {
    val dshPkgs = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai")
    val webDist = File(dshPkgs, "dsh-web-frontend/dist")
     val androidBridge = File(homeDir, ".dsh/profiles/web/node_modules/@dsh-android/dsh-android-bridge/lib/index.js")
    val home = File(homeDir, ".dsh")
     applyAssetPatch("patched/dsh-android-bridge-index.js", androidBridge)
    // 修复同一步多个 bash 并行导致回合被中断：把 agent-loop 默认工具并行度降为 1
    // （同一步的工具调用串行执行，一个完成后再启动下一个），见 patched/agent-loop-index.js。
    applyAssetPatch("patched/agent-loop-index.js",
      File(dshPkgs, "dsh-agent-loop/lib/index.js"))
    // v0.12.4 (rc8) migration: onImagePicked/describeImage/bundle-hardening/textzoom patches
    // were removed — rc8's official native image request (serializeRequestWithImages) and no-cache
    // hardening cover them; the textzoom feature was dropped after the settings-general rework
    // (the bridge method is kept).
    applyAssetPatch("patched/primitives-index.js",
      File(dshPkgs, "dsh-client-ui-primitives/lib/index.js"))
    applyAssetPatch("patched/attachment-local-index.js",
      File(dshPkgs, "dsh-attachment-local/lib/index.js"))
    applyAssetPatch("patched/web-frontend-index.html",
      File(webDist, "index.html"), hashAdaptive = true)
    // dsh 0.1.1-rc.2 bundles deepseek-v4-flash-vision-exp natively (with the corrected
    // image-request serialization), so the old rc.1 catalog overlay is obsolete — the native
    // file is left untouched.
    applyAssetPatch("patched/session-persistence-jsonl-index.js",
      File(dshPkgs, "dsh-session-persistence-jsonl/lib/index.js"))
    applyAssetPatch("patched/fs-local-index.js",
      File(dshPkgs, "dsh-fs-local/lib/index.js"))
  }

  /** Overwrite-style patch: applies when the target differs from the bundled asset (content
   *  fingerprint), so an updated asset re-applies on upgrade instead of being skipped by a stale
   *  marker string (the v1→v2 asset-update failure).
   *  hashAdaptive（2026-08-23，前端审核 CRITICAL#4）：web-frontend-index.html 引用引擎 dist 的
   *  content-hashed bundle 名（/assets/index-<hash>.js）。引擎升级 → hash 变化 → patched 模板
   *  仍指向旧 hash → 404 白屏。开启后：先从引擎现存 index.html 提取当前 hash 引用，再替换
   *  patched 模板中的旧引用（asset 模板本身可长期不随引擎更新）。 */
  private fun applyAssetPatch(asset: String, target: File, hashAdaptive: Boolean = false) {
    // Patches track bundle layouts: when the runtime no longer ships the patched package
    // (e.g. dsh-client-ui-primitives dropped from the dependency graph in dsh 0.1.1-rc.1),
    // stop applying instead of littering a dead overlay into to the tree.
    if (!target.parentFile.exists()) {
      Log.i(TAG, "runtime patch skipped (target package absent): $asset")
      return
    }
    val assetBytes = try {
      context.assets.open(asset).use { it.readBytes() }
    } catch (e: Exception) {
      Log.w(TAG, "runtime patch asset missing: $asset")
      return
    }
    val finalBytes = if (hashAdaptive) adaptIndexHashes(assetBytes, target) else assetBytes
    if (target.exists() && target.readBytes().contentEquals(finalBytes)) return
    try {
      target.parentFile?.mkdirs()
      target.writeBytes(finalBytes)
      Log.i(TAG, "runtime patch applied/updated: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }

  /**
   * 把 patched index.html 中旧的 /assets/index-*.js、vendor-*.js|css 引用替换为
   * 引擎 dist/index.html 当前实际引用的新 hash。提取失败（引擎 index 读不到/无匹配）
   * 时原样返回——此时与旧行为一致，宁可不注入也不写坏。
   * 匹配规则：引擎当前引用 `assets/<stem>-<hash>.<ext>`，patched 中存在
   * `assets/<stem>-<hash'>.<ext>`（同 stem/同 ext，hash 不同）→ 替换为新 hash。
   */
  private fun adaptIndexHashes(patched: ByteArray, engineIndex: File): ByteArray {
    return try {
      val current = engineIndex.readText()
      val p = patched.toString(Charsets.UTF_8)
      var out = p
      val refRe = Regex("(?:/|\")assets/([A-Za-z0-9_.-]+)-([A-Za-z0-9]{8})\\.(js|css)(?:\"| )")
      val curRefs = refRe.findAll(current)
      for (m in curRefs) {
        val stem = m.groupValues[1]
        val hash = m.groupValues[2]
        val ext = m.groupValues[3]
        val old = Regex("assets/" + Regex.escape(stem) + "-[A-Za-z0-9]{8}\\." + ext)
        out = out.replace(old, "assets/$stem-$hash.$ext")
      }
      out.toByteArray(Charsets.UTF_8)
    } catch (e: Exception) {
      Log.w(TAG, "index hash adaptation failed; keeping bundled patch: " + e.message)
      patched
    }
  }

  /** Append-style patch (for cordis.patch.yml, keeping the user's existing entries). */
  private fun applyAssetPatchAppend(asset: String, target: File, marker: String) {
    if (target.exists() && target.readText().contains(marker)) return
    try {
      val content = context.assets.open(asset).bufferedReader().use { it.readText() }
      target.parentFile?.mkdirs()
      val existing = if (target.exists()) target.readText() else ""
      val sep = if (existing.isNotBlank() && !existing.endsWith("\n")) "\n" else ""
      target.writeText(existing + sep + content)
      Log.i(TAG, "runtime patch appended: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }

  /**
   * 部署内置的捆绑 agent 预设（assets/presets/<id>/ → $DSH_HOME/.agent-presets/<id>/）。
   * 幂等：目标文件内容与资产一致则跳过（升级/快照刷新后自动重新应用）。
   * 当前捆绑：cordis-argfix（「创造模式（参数修复）」）——cordis_define 参数扁平化，
   * 修复模型把嵌套对象序列化为 JSON 字符串导致的 oneOf 校验失败。
   */
  fun deployBundledPresets() {
    val presetRoot = File(ensurePrivateDshData(), ".agent-presets")
    val rels = listOf(
      "agent.cordis.yml",
      "preset.yml",
      "plugins/argfix3.js",
      "skills/cordis-plugin-development/SKILL.md",
      "skills/editing-cordis-compositions/SKILL.md",
    )
    for (id in listOf("cordis-argfix")) {
      val dest = File(presetRoot, id)
      for (rel in rels) {
        try {
          val assetPath = "presets/$id/$rel"
          val bytes = context.assets.open(assetPath).use { it.readBytes() }
          val target = File(dest, rel)
          if (target.exists() && target.readBytes().contentEquals(bytes)) continue
          target.parentFile?.mkdirs()
          target.writeBytes(bytes)
          Log.i(TAG, "bundled preset deployed: $assetPath -> $target")
        } catch (e: Exception) {
          Log.e(TAG, "bundled preset deploy failed: presets/$id/$rel", e)
        }
      }
    }
  }

  /**
   * 部署手机端 UI 深度适配插件（@dsh-mobile/mobile-polish）。
   * 把 assets/mobile-polish/ 下的包文件写入 profile node_modules，
   * 并在 cordis.patch.yml 追加挂载条目（幂等，content-fingerprint + marker）。
   * 7 项适配：头部重叠修复、消息按钮精简、统计条精简、去点击闪烁、
   * 审批卡片上浮到输入框上方、新会话自动收抽屉、设置多级页面。
   */
  private fun deployMobilePolish() {
    val polishRoot = File(homeDir, ".dsh/profiles/web/node_modules/@dsh-mobile/mobile-polish")
    for ((rel, asset) in listOf(
      "package.json" to "mobile-polish/package.json",
      "lib/index.js" to "mobile-polish/lib/index.js",
      "lib/client.js" to "mobile-polish/lib/client.js",
    )) {
      try {
        val bytes = context.assets.open(asset).use { it.readBytes() }
        val target = File(polishRoot, rel)
        if (target.exists() && target.readBytes().contentEquals(bytes)) continue
        target.parentFile?.mkdirs()
        target.writeBytes(bytes)
        Log.i(TAG, "mobile-polish deployed: $asset -> $target")
      } catch (e: Exception) {
        Log.e(TAG, "mobile-polish deploy failed: $asset", e)
      }
    }
    val patch = File(homeDir, ".dsh/profiles/web/cordis.patch.yml")
    applyAssetPatchAppend("mobile-polish/cordis.append.yml", patch, "@dsh-mobile/mobile-polish")
  }

  /**
   * 部署 Agnes 多模态插件（dsh-agconfig / dsh-agimage / dsh-agvideo）。
   * 把 assets/dsh-ag 系列 下的包文件写入 profile node_modules，并在 cordis.patch.yml
   * 追加挂载条目（幂等，content-fingerprint + marker）。移动端 host 半已由
   * pwsh 移植为 Node fetch（Android 无 PowerShell）。
   */
  private fun deployAgPlugins() {
    val profileModules = File(homeDir, ".dsh/profiles/web/node_modules")
    val patch = File(homeDir, ".dsh/profiles/web/cordis.patch.yml")
    for (name in listOf("dsh-agconfig", "dsh-agimage", "dsh-agvideo", "dsh-zh-mode", "dsh-mobile-persona")) {
      val pkgRoot = File(profileModules, name)
      for ((rel, asset) in listOf(
        "package.json" to "$name/package.json",
        "lib/index.js" to "$name/lib/index.js",
        "lib/client.js" to "$name/lib/client.js",
      )) {
        try {
          val bytes = context.assets.open(asset).use { it.readBytes() }
          val target = File(pkgRoot, rel)
          if (target.exists() && target.readBytes().contentEquals(bytes)) continue
          target.parentFile?.mkdirs()
          target.writeBytes(bytes)
          Log.i(TAG, "ag plugin deployed: $asset -> $target")
        } catch (e: Exception) {
          Log.e(TAG, "ag plugin deploy failed: $asset", e)
        }
      }
      applyAssetPatchAppend("$name/cordis.append.yml", patch, name)
    }

    // 确保 .credentials.yaml 权限为 600（owner-only），否则 credentials-local 拒绝加载导致引擎挂掉
    val credFile = File(homeDir, ".dsh/.credentials.yaml")
    if (credFile.exists()) {
      credFile.setReadable(false, false)
      credFile.setReadable(true, true)
      credFile.setWritable(false, false)
      credFile.setWritable(true, true)
    }
  }


  /** Deploy the embedded PPT Master skill into DSH's canonical global skills directory. */
  private fun deployBundledPptSkill() {
    val staging = File(homeDir, ".dsh/skills/.ppt-master-${UUID.randomUUID()}")
    try {
      val expected = context.assets.open("ppt_master.sha256").bufferedReader().use { it.readText().trim().lowercase() }
      if (expected.isBlank()) throw IllegalStateException("ppt_master.sha256 is empty")
      if (pptSkillMarker.isFile && pptSkillMarker.readText().trim().lowercase() == expected &&
        File(pptSkillDir, "SKILL.md").isFile) return

      staging.deleteRecursively()
      staging.mkdirs()
      val zipBytes = context.assets.open("ppt_master.zip").use { it.readBytes() }
      val actual = MessageDigest.getInstance("SHA-256").digest(zipBytes)
        .joinToString("") { "%02x".format(it) }
      if (actual != expected) throw SecurityException("ppt-master archive SHA-256 mismatch")
      ZipInputStream(ByteArrayInputStream(zipBytes).buffered()).use { zip ->
          var entry = zip.nextEntry
          var count = 0
          var bytes = 0L
          while (entry != null) {
            count++
            if (count > 20_000) throw SecurityException("ppt-master archive has too many entries")
            val raw = entry!!.name.replace('\\', '/')
            val relative = raw.trimStart('/')
            if (relative.isEmpty() || relative.split('/').any { it == ".." }) {
              throw SecurityException("unsafe ppt-master archive path: $raw")
            }
            val target = File(staging, relative)
            val base = staging.canonicalFile
            if (!target.canonicalFile.path.startsWith(base.path + File.separator)) {
              throw SecurityException("ppt-master archive escapes staging directory")
            }
            if (entry!!.isDirectory) {
              target.mkdirs()
            } else {
              target.parentFile?.mkdirs()
              FileOutputStream(target).use { output ->
                val buffer = ByteArray(64 * 1024)
                while (true) {
                  val n = zip.read(buffer)
                  if (n < 0) break
                  bytes += n
                  if (bytes > 32L * 1024 * 1024) throw SecurityException("ppt-master archive is too large")
                  output.write(buffer, 0, n)
                }
              }
            }
            zip.closeEntry()
            entry = zip.nextEntry
          }
        }
      val skill = File(staging, "SKILL.md")
      if (!skill.isFile) throw IllegalStateException("ppt-master archive has no SKILL.md")
      // The bundled phone skill uses a portable data-root placeholder.
      // Resolve it to this app's DSH_HOME parent before activation.
      val dataRoot = File(homeDir, ".dsh").absolutePath
      staging.walkTopDown().filter { it.isFile && (it.extension == "md" || it.extension == "sh") }.forEach { file ->
        val text = file.readText()
        if (text.contains("${'$'}{DATA_DIR}")) file.writeText(text.replace("${'$'}{DATA_DIR}", dataRoot))
      }
      val old = File(homeDir, ".dsh/skills/ppt-master.old")
      old.deleteRecursively()
      pptSkillDir.parentFile?.mkdirs()
      if (pptSkillDir.exists() && !pptSkillDir.renameTo(old)) {
        throw IllegalStateException("cannot stage existing ppt-master skill")
      }
      if (!staging.renameTo(pptSkillDir)) {
        if (old.exists()) old.renameTo(pptSkillDir)
        throw IllegalStateException("cannot activate bundled ppt-master skill")
      }
      pptSkillMarker.parentFile?.mkdirs()
      pptSkillMarker.writeText(expected + "\n")
      old.deleteRecursively()
      Log.i(TAG, "bundled ppt-master skill deployed")
    } catch (t: Throwable) {
      staging.deleteRecursively()
      Log.e(TAG, "bundled ppt-master deploy failed", t)
    }
  }

  /** Deploy the Android package client and PPT environment helper. */
  private fun deployPackageClient() {
    try {
      val clientBytes = context.assets.open(pkgClientAsset).use { it.readBytes() }
      if (!pkgClientFile.exists() || !pkgClientFile.readBytes().contentEquals(clientBytes)) {
        pkgClientFile.parentFile?.mkdirs()
        pkgClientFile.writeBytes(clientBytes)
        pkgClientFile.setReadable(false, false)
        pkgClientFile.setReadable(true, true)
      }

      val pkgWrapper = File(usrDir, "bin/pkg")
      val wrapper = "#!/system/bin/sh\n" +
        "exec \"${nodeBin.absolutePath}\" \"${pkgClientFile.absolutePath}\" \"\$@\"\n"
      val wrapperNeedsUpdate = Files.isSymbolicLink(pkgWrapper.toPath()) ||
        !pkgWrapper.exists() || pkgWrapper.readText() != wrapper
      if (wrapperNeedsUpdate) {
        if (Files.isSymbolicLink(pkgWrapper.toPath())) Files.delete(pkgWrapper.toPath())
        pkgWrapper.parentFile?.mkdirs()
        pkgWrapper.writeText(wrapper)
        if (!pkgWrapper.setExecutable(true, false)) Log.w(TAG, "pkg wrapper chmod failed")
      }

      val setupBytes = context.assets.open(pptSetupAsset).use { it.readBytes() }
      for (target in listOf(pptSetupFile, pptSkillSetupFile)) {
        if (!target.exists() || !target.readBytes().contentEquals(setupBytes)) {
          target.parentFile?.mkdirs()
          target.writeBytes(setupBytes)
          if (!target.setExecutable(true, false)) Log.w(TAG, "PPT setup chmod failed: " + target)
        }
      }
    } catch (t: Throwable) {
      Log.e(TAG, "Android package client deploy failed", t)
    }
  }

  /**
   * 修复 usr/bin/dsh（2026-08-26，插件市场安装失败根因）：
   * 快照里 dsh 是软链 → lib/node_modules/@deepseek-ai/dsh/lib/bin.js，
   * 其 shebang 为 `#!/usr/bin/env node`，Android 无 /usr/bin/env，且
   * termux-exec hook 在 force 模式下把无法识别的非 ELF 脚本路由到
   * linker64 → "bad ELF magic: 23212f75"。替换为 `#!/system/bin/sh`
   * 包装器，直接 exec node bin.js（LD_LIBRARY_PATH/OPENSSL_CONF 由
   * shellEnv 注入）。幂等：dsh 已是普通文件（非软链）→ 跳过。
   */
  private fun fixDshBin() {
    try {
      val dsh = File(usrDir, "bin/dsh")
      if (!dsh.exists() || !Files.isSymbolicLink(dsh.toPath())) return
      val node = nodeBin.absolutePath
      val script = "#!/system/bin/sh\n" +
        "# dsh-android wrapper: dsh -> node bin.js (no /usr/bin/env on Android)\n" +
        "exec $node " + dshBin.absolutePath + " \"$@\"\n"
      dsh.delete()
      dsh.writeText(script)
      if (!dsh.setExecutable(true)) Log.w(TAG, "dsh wrapper chmod failed")
      Log.i(TAG, "dsh bin fixed: symlink -> wrapper")
    } catch (t: Throwable) {
      Log.e(TAG, "dsh bin fix failed (non-fatal): " + t.message)
    }
  }

  /** Start the dsh web engine from the embedded snapshot. */
  fun startEngine(port: Int = 3080): Boolean {
    // Bundled presets and Android-side helpers must be in place before every
    // start attempt, including watchdog restarts after a runtime update.
    deployBundledPresets()
    deployBundledPptSkill()
    deployMobilePolish()
    deployAgPlugins()
    deployPackageClient()
    fixDshBin()
    // LD_PRELOAD depends on the snapshot's termux-exec lib: when missing, every child exec fails,
    // and combined with the cooldown window that means a silent 90s engine outage — assert explicitly
    // before starting and fail loudly if absent.
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    if (!preload.exists()) {
      Log.e(TAG, "engine start failed: termux-exec preload missing at " + preload.absolutePath)
      return false
    }
    val now = System.currentTimeMillis()
    // Process-level CAS: only one concurrent call really starts (device-measured EADDRINUSE double-start).
    if (!STARTING.compareAndSet(false, true)) return true
    // Cooldown window: no re-start within 90s of the last attempt (a cold boot takes 20-45s).
    // Review 2026-08-18 (L2 semantics): returning true here means "no further start needed"
    // (the engine is most likely already starting), not "this call started it successfully" — callers
    // poll engine reachability themselves, so this never causes a wrong wait, but it must not be
    // read as proof of success.
    // 2026-08-23 修复（审核 CRITICAL#1，用户实测"重试不 kill 旧引擎进程"）：冷却窗内若引擎
    // 实际不可达（探活 down），冷却窗不应阻止重试——旧实现让挂死进程占着 3080 直到 EADDRINUSE。
    // 同时 startEngine 前必须先终结残留进程：destroy() 仅 SIGTERM，引擎挂死时需 destroyForcibly。
    val withinCooldown = now - EngineManager.lastStartAttemptAt < START_COOLDOWN_MS
    val engineReachable = try { EngineProbe.check(300).optBoolean("running", false) } catch (_: Exception) { false }
    if (withinCooldown && engineReachable) {
      STARTING.set(false)
      LogCollector.log(TAG, "engine start skipped (cooldown window; engine reachable)")
      return true
    }
    if (withinCooldown && !engineReachable) {
      LogCollector.log(TAG, "engine start: cooldown bypassed (engine unreachable after " + (now - EngineManager.lastStartAttemptAt) + "ms)")
    }
    return try {
      // 旧进程清理：无论句柄是否还在，先终结残留（引擎挂死/内存里 fork 掉的孤儿）。
      killExistingEngine()
      applyRuntimePatches()
      // --no-open: the engine must never try to open a desktop browser on Android
      // (the WebView IS the UI). Without it, rc.2's spawn xdg-open on a missing
      // binary stalls engine serve on some emulators (MuMu root observed);
      // the flag is the official engine CLI switch (see bin.js docs).
      val args = arrayOf(
        nodeBin.absolutePath, "--expose-internals", dshBin.absolutePath, "web", "--port", port.toString(), "--no-open",
      )
      engineProcess = startWithArgs(args, shellEnv())
      // The cooldown is written only after a real start: failure paths don't consume the window (retry is immediate).
      EngineManager.lastStartAttemptAt = now
      LogCollector.log(TAG, "engine started")
      true
    } catch (t: Throwable) {
      Log.e(TAG, "engine start failed", t)
      LogCollector.log(TAG, "engine start FAILED: " + (t.message ?: t.javaClass.simpleName))
      false
    } finally {
      STARTING.set(false)
    }
  }

  /**
   * Spawn the engine, falling back to the system linker when the direct exec
   * is denied: Android 15+ apps targeting SDK 35+ may not exec app-data ELF
   * binaries, but loading them through /system/bin/linker64 is the same
   * mechanism as native libraries (always permitted for app data).
   */
  private fun startWithArgs(args: Array<String>, env: Map<String, String>): Process {
    val log = File(context.filesDir, "engine.log")
    fun build(argv: List<String>): ProcessBuilder =
      ProcessBuilder(argv).also { b ->
        b.environment().putAll(env)
        b.redirectErrorStream(true)
        b.redirectOutput(log)
      }
    return try {
      build(args.toList()).start()
    } catch (e: java.io.IOException) {
      if (e.message?.contains("Permission denied") != true) throw e
      Log.w(TAG, "direct exec denied, falling back to linker64: " + e.message)
      build(listOf("/system/bin/linker64") + args.toList()).start()
    }
  }

  /** Stop the engine process (best-effort). */
  fun stopEngine() {
    engineProcess?.destroy()
    engineProcess = null
    LogCollector.log(TAG, "engine stopped (manual)")
    // Reset the cooldown after a manual stop: returning to the foreground should allow an immediate restart.
    EngineManager.lastStartAttemptAt = 0
  }

  /**
   * 终结残留引擎进程：先杀持有句柄的（destroyForcibly + waitFor 有界等待），
   * 再兜底 pkill 快照 node 进程（处理服务/看门狗曾被 fork、句柄已被覆盖的孤儿）。
   * 幂等：无残留时零动作。绝不等待超过 5s（不阻塞启动路径）。
   */
  private fun killExistingEngine() {
    val held = engineProcess
    if (held != null) {
      try {
        held.destroy()
        if (!held.waitFor(3, java.util.concurrent.TimeUnit.SECONDS)) {
          held.destroyForcibly()
          held.waitFor(2, java.util.concurrent.TimeUnit.SECONDS)
        }
      } catch (_: Throwable) {
      }
      engineProcess = null
    }
    // 兜底：命中快照 node 的残留进程（`bin.js web` 是该引擎的唯一形态；pnpm/脚本子进程
    // 不含 bin.js web 特征，不会被误杀）。pkill 不可用时静默跳过。
    // 注：与 UpdateManager 的既有清理（pkill -f bin.js）口径一致。
    try {
      Runtime.getRuntime().exec(arrayOf("/system/bin/pkill", "-f", "bin.js")).waitFor()
    } catch (_: Throwable) {
    }
  }

  /** Reset the 90s cooldown window: auto-undo (config rollback) or user retry
   *  must be allowed to start the engine immediately. Manual stop already does this. */
  fun resetCooldown() {
    EngineManager.lastStartAttemptAt = 0
  }

  /**
   * Update-manager-v2 probe state machine (PRD F3.2/F1.10): after an online
   * snapshot swap, `usr-old` is kept and `.update-pending` is set. Each engine
   * probe result feeds this: N consecutive healthy ticks finalize (delete the
   * old runtime); a pending window that never turns healthy rolls back to the
   * previous runtime (second-layer fallback; the F3 plugin layer stays in
   * charge of config/plugin-code rollbacks). Never throws.
   */
  fun onEngineProbe(healthy: Boolean) {
    val pending = File(context.filesDir, ".update-pending")
    if (!pending.exists()) {
      updateHealthTicks = 0
      return
    }
    if (healthy) {
      updateHealthTicks++
      if (updateHealthTicks >= UPDATE_CONFIRM_TICKS) {
        pending.delete()
        File(context.filesDir, ".update-pending-at").delete()
        File(context.filesDir, "usr-old").deleteRecursively()
        updateHealthTicks = 0
        LogCollector.log(TAG, "update confirmed: old runtime cleaned (usr-old removed)")
      }
    } else {
      updateHealthTicks = 0
      val at = File(context.filesDir, ".update-pending-at").takeIf { it.exists() }?.readText()?.trim()?.toLongOrNull()
      if (at != null && System.currentTimeMillis() - at > UPDATE_ROLLBACK_MS) {
        rollbackToOld()
        pending.delete()
        File(context.filesDir, ".update-pending-at").delete()
      }
    }
  }

  /** Swap the current runtime back to the kept previous one; restarts the engine from it. */
  private fun rollbackToOld() {
    val usr = File(context.filesDir, "usr")
    val old = File(context.filesDir, "usr-old")
    if (!old.exists()) return
    try {
      val broken = File(context.filesDir, "usr-broken")
      broken.deleteRecursively()
      if (usr.exists()) usr.renameTo(broken)
      if (old.renameTo(usr)) {
        LogCollector.log(TAG, "update rolled back to previous runtime; restarting engine")
        EngineManager.lastStartAttemptAt = 0 // allow an immediate restart (no cooldown stall)
        try { startEngine() } catch (_: Throwable) {
        }
      } else {
        // Rollback of the rollback: the failed old-swap left no usr — put the broken new one back.
        if (!usr.exists() && broken.exists()) broken.renameTo(usr)
        Log.e(TAG, "update rollback failed; usr restored from usr-old: " + usr.exists())
      }
    } catch (t: Throwable) {
      Log.e(TAG, "update rollback threw", t)
    }
  }

  /**
   * Snapshot environment shared by engine/console/log processes (PATH/LD_LIBRARY_PATH/HOME/DSH_HOME/
   * TERMUX_* injected explicitly — the snapshot is self-sufficient, no Termux app needed). Idempotent:
   * safe to call repeatedly (ensurePrivateDshData and the TMPDIR mkdirs are both idempotent).
   */
  fun shellEnv(): Map<String, String> {
    deployPackageClient()
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    val pkgEndpoint = try {
      TermuxPackageService.ensure(context, usrDir)
    } catch (t: Throwable) {
      Log.w(TAG, "package service unavailable: " + (t.message ?: t.javaClass.simpleName))
      null
    }
    // Cert paths hardcoded at Termux package build time (/data/data/com.termux/...) break after the
    // PREFIX relocation; relocate-snapshot.py doesn't rewrite ELF, so env vars cover the functional
    // paths — curl/wget/git https CA validation depends on them (v0.12.3-FX-2).
    val cert = File(usrDir, "etc/tls/cert.pem").takeIf { it.exists() }
    val certEnv = if (cert != null) {
      mapOf(
        "SSL_CERT_FILE" to cert.absolutePath,
        "CURL_CA_BUNDLE" to cert.absolutePath,
        "GIT_SSL_CAINFO" to cert.absolutePath,
        // 快照 node 编译期硬编码 OpenSSL 配置路径 /data/data/com.termux/...（app 域不可读）：
        // 不注入则任何 node/npm 子进程启动即 OpenSSL configuration error 退出（agent 工具调用
        // npm/node 全部失败，引擎本体侥幸存活）。与 UndoGate/AdbState 同一修复（坑 #5 统一到
        // 引擎级 env，覆盖 agent 所有工具子进程，2026-08-24 真机实测实锤）。
        "OPENSSL_CONF" to File(usrDir, "etc/tls/openssl.cnf").absolutePath,
      )
    } else emptyMap()
    return mapOf(
      "PREFIX" to usrDir.absolutePath,
      "PATH" to (usrDir.absolutePath + "/bin:/system/bin"),
      "LD_LIBRARY_PATH" to (usrDir.absolutePath + "/lib"),
      "HOME" to homeDir.absolutePath,
      // DSH_HOME always stays in the private domain (FUSE forbids symlinks, so the public domain
      // can't maintain the profiles/node_modules flat fallback); all runtime user data lives in private
      // files/home/.dsh, and public Documents/dshdata is only the export repo.
      "DSH_HOME" to ensurePrivateDshData().absolutePath,
      // os.tmpdir() falls back to the baked-in Termux tmp on Android
      // (unwritable from the app domain); keep spill inside filesDir.
      "TMPDIR" to File(homeDir, "tmp").apply { mkdirs() }.absolutePath,
      // Android 16 forbids exec of app-data ELF regardless of targetSdk
      // (observed on Android 16/vivo: direct exec EACCES even at targetSdk
      // 34). Termux's execve hook re-routes denied execs through
      // /system/bin/linker64 (same mechanism as JNI libs); the snapshot
      // ships libtermux-exec-*-ld-preload.so. The hook only rewrites for
      // untrusted_app_25/27 SELinux domains, so force mode is required.
      "LD_PRELOAD" to preload.absolutePath,
      "TERMUX_EXEC__SYSTEM_LINKER_EXEC__MODE" to "force",
      "TERMUX_EXEC__EXECVE_CALL__INTERCEPT" to "1",
      "TERMUX__ROOTFS" to usrDir.parentFile.absolutePath,
      "TERMUX__PREFIX" to usrDir.absolutePath,
      "TERMUX_APP__DATA_DIR" to context.filesDir.parentFile.absolutePath,
      "TERMUX_APP__LEGACY_DATA_DIR" to "/data/data/com.dsharnessmobile.shell",
      "TERMUX_VERSION" to BuildConfig.TERMUX_VERSION,
      // Android-native package service: pkg wrapper talks only to this process-local endpoint.
      "DSH_PKG_URL" to (pkgEndpoint?.url ?: ""),
      "DSH_PKG_TOKEN" to (pkgEndpoint?.token ?: ""),
      "DSH_PKG_ENDPOINT" to File(context.filesDir, ".dsh-pkg-endpoint").absolutePath,
      "DPKG_ADMINDIR" to File(usrDir, "var/lib/dpkg").absolutePath,
      // Directory-picker endpoint auth token (validated by the web-compat plugin via x-dsh-pick-token).
      "DSH_PICK_TOKEN" to (pickToken ?: ""),
      // ADB 授权状态（0.13.0 F1.7）：dsh-android-bridge 插件据此失败关闭；门控=完全访问档位+开关+配对。
      "DSH_ADB_ALLOW" to (if (AdbState.allowSwitch(context)) "1" else "0"),
      "DSH_ADB_PAIRED" to (if (AdbState.paired(context)) "1" else "0"),
      "DSH_ADB_WIRELESS" to (if (AdbState.paired(context)) "1" else "0"),
      // 门1「完全访问档位」= All Files Access（系统权限）——引擎侧判定与壳侧 AdbState.fullAccess() 同源
      // （审校 C6 语义分裂修复：此前引擎把「写面档位」误当门1，见 review 文档）；授予后重启引擎生效。
      "DSH_ADB_FULLACCESS" to (if (AdbState.fullAccess()) "1" else "0"),
      // Vision backend (Qwen-VL) API key: read from a private file rather than hardcoded in source.
      "DASHSCOPE_API_KEY" to (File(context.filesDir, "dashscope-key.txt").takeIf { it.exists() }?.readText()?.trim() ?: ""),
      // DeepSeek 官方 provider（dsh-llm-deepseek，provider=deepseek-official）：同模式私有文件注入。
      "DEEPSEEK_API_KEY" to (File(context.filesDir, "deepseek-key.txt").takeIf { it.exists() }?.readText()?.trim() ?: ""),
    ) + certEnv
  }

  companion object {
    private const val TAG = "dsh-engine"

    /** Healthy ticks (each 5s watchdog poll) required before the update-v2 finalize deletes usr-old. */
    const val UPDATE_CONFIRM_TICKS = 3

    /** Pending window before an unhealthy runtime is rolled back (PRD F3: recovery ≤ 3 min). */
    const val UPDATE_ROLLBACK_MS = 180_000L

    /** Watchdog/retry backoff: no new start within this window of the last
     *  attempt. Cold node boot on the phone takes 20-45s (plugin tree + first
     *  bind); a 5s watchdog poll would otherwise race a healthy boot and
     *  double-start the engine (device-observed EADDRINUSE). 90s covers the
     *  slowest observed boot with margin. */
    const val START_COOLDOWN_MS = 90_000L

    /** Process-level start CAS: visible across EngineManager instances (double-start race guard). */
    val STARTING = java.util.concurrent.atomic.AtomicBoolean(false)

    /** Last real start time (epoch ms); the watchdog cooldown-window baseline. */
    @Volatile
    var lastStartAttemptAt: Long = 0

    /**
     * Process-level shared directory-picker auth token (C1 fix, 2026-08-16):
     * generated once, then reused by every EngineManager instance in the process — MainActivity
     * rebuilds and EngineService watchdog engine restarts never lose/rotate the token, so auth stays
     * consistent even after the engine-side fail-closed (empty token → reject) path.
     */
    @Volatile
    var sharedPickToken: String? = null

    /** Get (or generate on first call) the process-level pick token. */
    fun ensurePickToken(): String {
      sharedPickToken?.let { return it }
      val token = java.util.UUID.randomUUID().toString()
      sharedPickToken = token
      return token
    }
  }
}
